/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASpace: typeof import('ant-design-vue/es')['Space']
    AutoImportTest: typeof import('./src/core/components/AutoImportTest.vue')['default']
    Dashboard: typeof import('./src/modules/views/Dashboard.vue')['default']
    Forbidden: typeof import('./src/modules/views/Forbidden.vue')['default']
    Login: typeof import('./src/modules/views/Login.vue')['default']
    NotFound: typeof import('./src/modules/views/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderCaptcha: typeof import('./src/core/components/SliderCaptcha.vue')['default']
    UserDetail: typeof import('./src/modules/user/views/UserDetail.vue')['default']
    UserList: typeof import('./src/modules/user/views/UserList.vue')['default']
    UserManagement: typeof import('./src/modules/views/UserManagement.vue')['default']
  }
}
